# ===== File: .streamlit/secrets.toml =====
# Store your OpenAI key securely here
defaults = { }

# Example:
OPENAI_API_KEY = "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"
